### ISSUE TITLE
Could see a lot of junk data in user interface

### ISSUE THREAD

**Issue by iarora93** [airavata-courses/CodeNinja502#11]

**Comment by arswaroop** [comment]
Date is getting displayed as junk. Working on fixing it

**Comment by arswaroop** [comment]
Have fixed our fetch component to show relative time of post. in the following commit-

15398daec204c0999a03713e1bd472616f9c9dc3

Please confirm for closure

**Comment by morparia-p** [comment]
Have displayed domain of the project, which was not parsed correctly in previous versions.

https://github.com/airavata-courses/CodeNinja502/tree/Assignment-1 

Please take a look at the changes

**Comment by morparia-p** [comment]
Have displayed domain of the project, which was not parsed correctly in previous versions.

https://github.com/airavata-courses/CodeNinja502/commit/6ecd59efa37a42ec434f2e4e87df67cd94a86983

Please take a look at the changes

**Comment by morparia-p** [comment]
In the above commit, have resized the image to improve the feed and improved the design of the page

**Comment by iarora93** [comment]
Perfect as of now
