### ISSUE TITLE
No proper Input Validations

### ISSUE THREAD

**Issue by iarora93** [airavata-courses/CodeNinja502#12]

**Comment by morparia-p** [comment]
Have raised a [commit - d4bb2d6](https://github.com/airavata-courses/CodeNinja502/commit/d4bb2d638b7945e883546d9c6bf686eb251fc58a) to validate the Description field. Please review to close the issue

**Comment by iarora93** [comment]
Hello @morparia-p ,

Looks much better now.
But when i click on description field for a sec a white screen comes up.
But other than that all good as of now
