### ISSUE TITLE
Assignment 1 peer review issues

### ISSUE THREAD

**Issue by BBaggines** [airavata-courses/CodeNinja502#16]

**Comment by BBaggines** [comment]
Issues for first assignment peer-review by Shradha:
1. #17
2. #19 
3. #18 
4. #20

**Comment by BBaggines** [comment]
A few things(trivial) which came to my attention:
1. On logging in, home page showed a few previous comments which i believe should not be the case. 
2. A few more details regarding the project can be thought of as a mere description box feels a bit inadequate.

Apart from this, the steps were precise and clear. I did not face any issues while trying to get the project up and running. Good work at documentation!

**Comment by morparia-p** [comment]
Thanks for the review and suggestions. We would consider accomplishing them them in our future milestones.
