### ISSUE TITLE
Branches naming convention and assignment-1 branch

### ISSUE THREAD

**Issue by BBaggines** [airavata-courses/CodeNinja502#17]
The branch assignment-1 has all the microservices merged into a single branch which might create problems in the long run. One of the solutions mentioned during the lecture by Marlon was to create one specific branch for each microservice and merge them into their individual release branches. 
ALso, the naming convention of the individual branches are not followed which is making it difficult to identify them.

**Comment by morparia-p** [comment]
Hey @BBaggines ,

Thanks for highlighting the issue. We will clear the branches soon.

**Comment by morparia-p** [comment]
Hey @BBaggines , 
Thanks for bringing up the issue. It helped us while deploying the services no separate servers. Will close the issue for now.
