### ISSUE TITLE
Error while trying to run Image upload service

### ISSUE THREAD

**Issue by BBaggines** [airavata-courses/CodeNinja502#19]
Hey,
I was trying to run the Image upload service but it is giving me the below error while executing the last command. 

![image](https://user-images.githubusercontent.com/6296880/52529381-c01c4f80-2cbe-11e9-987c-4c26bedbf9a8.png)

**Comment by morparia-p** [comment]
Hey @BBaggines ,

Did the new commit resolve the the issue? Let us know if you're still facing problems running image upload service.

**Comment by BBaggines** [comment]
> Hey @BBaggines ,
> 
> Did the new commit resolve the the issue? Let us know if you're still facing problems running image upload service.

Hey!
Yeah it did!
