### ISSUE TITLE
Project milestone #1 issues

### ISSUE THREAD

**Issue by cbrahme** [airavata-courses/CodeNinja502#21]
#21 When I try to register as a new user, on click of 'Register' I am not getting redirected to a new page.

**Comment by morparia-p** [comment]
Hi @cbrahme ,

Thanks for raising the issue.

Have resolved the issue along with #12  and committed https://github.com/airavata-courses/CodeNinja502/commit/69a0a8c92eb8d9c585936fbc8f953920a87116bb here.

Let me know if you still face the same issue.

**Comment by cbrahme** [comment]
@morparia-p Registration is working fine now. 
Thank you!
