### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/CodeNinja502#25]
Hey team,

I just started with the code review. Will update my progress/issues here.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Please share the login credentials to run "feed-fetch-service-0.0.7.jar" from https://github.com/airavata-courses/CodeNinja502/tree/Assignment-1 .

**Comment by PulkitMathur** [comment]
Sent you the login credentials file via email.

**Comment by nawazkh** [comment]
Thanks Pulkit! 

I am facing an issue with running the service in GO.
<img width="897" alt="screen shot 2019-02-21 at 2 44 00 am" src="https://user-images.githubusercontent.com/25679594/53152071-a57d8c80-3582-11e9-90cd-c6ac9d01a734.png">

Is it something wrong at my end?

**Comment by arswaroop** [comment]
Hey Nawaz. Guess the azure DB instance went down. Will let you know once I fix it.

**Comment by nawazkh** [comment]
Please let me know once you have fixed it.

Thanks,
Nawaz

**Comment by morparia-p** [comment]
Hey @nawazkh ,

Have updated the code to connect to a new DB instance as well as mailed a file to you. Please do let us know if you're facing more issues.

**Comment by nawazkh** [comment]
Hey Team, 

I am testing the project, And I am facing the same error again. 
<img width="1073" alt="screen shot 2019-02-25 at 11 49 30 am" src="https://user-images.githubusercontent.com/25679594/53353758-743eec80-38f3-11e9-9274-2f8ea5eaff65.png">

Please follow up with me on slack.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hey Team,

I changed the login.xml sent by @morparia-p , but I am still facing the same issue.

<img width="1073" alt="screen shot 2019-02-25 at 11 49 30 am" src="https://user-images.githubusercontent.com/25679594/53354111-2080d300-38f4-11e9-9f2f-89a70b91e1f6.png">

Edit 1: Is it not advisable to build a new jar every time from the source code than using a pre built jar for the Java Microservice?

**Comment by arswaroop** [comment]
Hey Nawaz,
For me it isnt giving any error. I will test this on some other systems and will get back to you.

**Comment by arswaroop** [comment]
Hi Nawaz,
Go has adopted the mongoDB driver officially and since then (5 days ago) has changed the implementation of mongoDB driver library. I have updated the code. and pushed to the branch.
Please pull the updated code. (refer to this issue : https://github.com/airavata-courses/CodeNinja502/issues/26 )
Also we need to run new import commands. I am pasting them below for your convenience. I will update the wiki as well-

```
go get "go.mongodb.org/mongo-driver/mongo"

go get "go.mongodb.org/mongo-driver/bson"

go build 

go run "main.go"

```

**Comment by nawazkh** [comment]
Hey Team, 

Finally completed testing the project. It's a great project! Micro-services were working great! 

Here is my summary: 
1. _Java microservice_ :, since we are in an open-source setup, it is advisable that the user gets to build the jar in his system rather than using a prebuilt jar. Please update the documentation for that. 
2. _Project_ : I could create posts on the website, but I was wondering if I could do anything more apart from adding posts? It is a great concept and adding more functionality like viewing selected projects can be great! 
3. In your wiki, please mention which microservice is serving what purpose. Also please mention the language it was developed in.

Keep up the good work! 

Thanks,
Nawaz
