### ISSUE TITLE
[WIKI] Explanation needed for Service Registration and Discovery

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/CodeNinja502#37]
On the wiki page, the Service Registration and Discovery section is left empty. You need to explain about the Consul Service Registration & discovery steps

**Comment by arswaroop** [comment]
Hi Chirag,
I have added Service Registration and Discovery features that i have used in the project.
Let me know in case you need any more information.

**Comment by Chirag-Galani** [comment]
Hey,
Looks good to me.
