### ISSUE TITLE
Peer Evaluation Milestone 2

### ISSUE THREAD

**Issue by ATarfe** [airavata-courses/CodeNinja502#39]
Hello Team CodeNinja502,

I went through the Wiki, which was pretty clear and descriptive of the main idea of the project. 
Can you guys share the Jenkins credentials for testing the deployment of the application? 
Here is my email id for sharing the same : atarfe@iu.edu.

Thanks.

**Comment by morparia-p** [comment]
Thanks for asking @ATarfe . Did you get a chance to look over jenkins and the project over-all?

**Comment by ATarfe** [comment]
Yes, I did tried testing the CI/CD. Building the fetch service took unexpectedly long time before failing.
I am raising an issue for the same. Other than that, the application functioned properly.
