### ISSUE TITLE
Summary (of Peer Review) Milestone 2

### ISSUE THREAD

**Issue by ATarfe** [airavata-courses/CodeNinja502#41]
Following are my thoughts after the review of the project:

1. Documentation was precise and up to the mark.
2. The napkin diagram and the architecture diagram is sufficient for describing the main idea.
3. The application worked fluently.
4. Had trouble building fetch service #40 .
5. The likes in each of the posts is hard-coded. #33 
6. Maybe you can add more details for the user which can help in connecting with relevant users.

Good job.

Thanks and Regards,
Amey Avinash Tarfe

**Comment by PulkitMathur** [comment]
I just updated the Wiki. Please try again and let me know if there is any issue.
