### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/CodeNinja502#78]
Hey Guys,

I am not able to signup new user. It does not give any error, just doesn't respond. Can you please check if its working.
If it's an issue, can you provide some credentials for me to login.

<img width="1552" alt="Screen Shot 2019-04-28 at 4 41 06 PM" src="https://user-images.githubusercontent.com/2353327/56869902-3b93c000-69d5-11e9-87fc-9c98a3425eb3.png">

**Comment by maheshbelnekar** [comment]
Ok, so after waiting a while, I finally got an error.
<img width="1552" alt="Screen Shot 2019-04-28 at 4 48 33 PM" src="https://user-images.githubusercontent.com/2353327/56869921-7dbd0180-69d5-11e9-8ae8-0f6d710d0e34.png">

**Comment by maheshbelnekar** [comment]
OK, so I tried again, and this time got another error.
<img width="1552" alt="Screen Shot 2019-04-28 at 4 50 28 PM" src="https://user-images.githubusercontent.com/2353327/56869940-ddb3a800-69d5-11e9-8922-f2662551f877.png">

**Comment by morparia-p** [comment]
Hey @maheshbelnekar there was a misconfiguration in the green deployment of login. We recognized and corrected the config and its working now. Let me know if you can get it working.
